### PR TITLE
Bike processing changes:

### PR DESCRIPTION
**Pull request by wtruitt3**
-handled temp stations for chicago - combined them with the stations that theybecome to create one station
-added a check for date errors - this only happened in dc for 02/2021 because of duplicate stations that were formatted incorrectly, these stations were removed (8)
-put the check for unique names before the check for bad stations, this is because some bad stations are actually duplicates of others

### CODE REVIEW

**Comment by aberke** [comment]
Can you report on how many stations change for each city and year?
It might be helpful to make a table / csv with columns like the following to understand the change
```
City | year | Total bike-share stations
```

**Comment by wtruitt3** [comment]
just added a csv that compares the number of bikes in each study area for each year

**Comment by aberke** [comment]
what's your evaluation?
It looks like some of the changes in the later years for philly and nyc might be relatively large.
Should definitely redo the analysis.

**Comment by wtruitt3** [comment]
Yes I have the same observation, I updated the Gini figures in the google doc and the table with the gini indexes, there does seem to be changes but nothing that changes the analysis to where we need to re-write

**Comment by wtruitt3** [comment]
I'm updating the big table at the bottom now

**Comment by wtruitt3** [comment]
I pushed my new changes to a separate branch and created a new pull request that has all of these changes with it as well so we can close this request and use the one I just opened if that sounds right

**Comment by aberke** [comment]
Sure. For future reference you might also be able to push a new commit to an open PR.

**Pull request closed without merging**
